### ISSUE TITLE
Kdenlive and melt crash on Ubuntu 18.04

### ISSUE THREAD

**Issue by ydesgagn** [mltframework/mlt-scripts#25]
Using the build kdenlive or build melt scripts on Ubuntu 18.04 always produce crashing binaries.

`
OpenCV Error: Assertion failed (total() == 0 || data != NULL) in Mat, file /usr/include/opencv2/core/mat.inl.hpp, line 464
terminate called after throwing an instance of 'cv::Exception'
  what():  /usr/include/opencv2/core/mat.inl.hpp:464: error: (-215) total() == 0 || data != NULL in function Mat
`

Does anything need to be updated in those scripts to work with the latest?

Thanks

**Comment by ddennedy** [comment]
build-kdenlive.sh is no longer supported for building a usable app as of KDE Frameworks 5. It really only remains for automated nightly build bots for basic checking kdenlive still compiles successfully against MLT when it changes. Use the Kdenlive website for Kdenlive builds.

The other problem with build-melt.sh  is probably due to frei0r OpenCV plugins facebl0r and facedetect.  Try removing those corresponding .so files in lib/frei0r-1 and see if it works.

**Comment by ddennedy** [comment]
If the above workaround succeeds you can try this untested change:
```
diff --git a/build/build-melt.sh b/build/build-melt.sh
index f5aebcf..98f1677 100755
--- a/build/build-melt.sh
+++ b/build/build-melt.sh
@@ -517,7 +517,7 @@ function set_globals {

   ####
   # frei0r
-  CONFIG[2]="./configure --prefix=$FINAL_INSTALL_DIR --libdir=$FINAL_INSTALL_DIR/lib"
+  CONFIG[2]="cmake -DCMAKE_INSTALL_PREFIX=$FINAL_INSTALL_DIR -DWITHOUT_OPENCV=1"
   CFLAGS_[2]=$CFLAGS
   LDFLAGS_[2]=$LDFLAGS

```

**Comment by ydesgagn** [comment]
Closing. Found the faulty frei0r OpenCV plugins.
