### ISSUE TITLE
melt issue with libmlt.so.6

### ISSUE THREAD

**Issue by rorito** [mltframework/mlt-scripts#5]
Got a compile working with the build-melt.sh script, trying to run the melt binary on Ubuntu 14.04 on Heroku.

From the compile, I added the bin and lib dir to our heroku app. I added the lib dir to my LD_LIBRARY_PATH.

When I run melt, I get:
./melt: error while loading shared libraries: libmlt.so.6: cannot open shared object file: No such file or directory

In my lib dir, I have libmlt.so.0.9.7 instead of libmlt.so.6.

Any help would be great.

**Comment by ddennedy** [comment]
In a typical install, libmlt.so.6 is symbolically linked to libmlt.so.0.9.7. .6 version is the ABI version and is what is linked to. 0.9.7 is the implementation (logical) version of that ABI. It appears that whatever you are doing to set LD_LIBRARY_PATH is not working. You should just copy all of the files in the install dir and run the melt wrapper script instead of the binary directly. The wrapper script sets all of the environment variables that are needed (more than just LD_LIBRARY_PATH - just as more than bin and lib needs to be copied).

This is not a trouble-support system; it is a defect tracking mechanism, and this is not a defect.
